// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utaploovdycvvuuitwpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0YXBsb292ZHljdnZ1dWl0d3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODU5MzIsImV4cCI6MjA3Mzc2MTkzMn0.TB7KJaAiQUiRBsd7gQtFSSOF0XeiLsIoyNfzEFiWw1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});